// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pet_Shop.Data;

#nullable disable

namespace PetShop.Migrations
{
    [DbContext(typeof(PetShopContext))]
    [Migration("20221117205403_Intial-Create")]
    partial class IntialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pet_Shop.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimalId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnimalId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 2,
                            CategoryId = 1,
                            Description = "The American Pit Bull Terrier has been known by many names, including the Pit Bull and the American Bull Terrier. It is often confused with the American Staffordshire Terrier, however, the United Kennel Club recognizes the American Pit Bull Terrier as its own distinct breed. Affectionately known as \"Pitties,\" the Pit Bull is known for being a loyal, protective, and athletic canine breed.",
                            Name = "American Pit Bull Terrier",
                            PictureName = "American Pit Bull Terrier.jpg"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 1,
                            CategoryId = 1,
                            Description = "The Boxer as it is known today was imported to the United States from Germany in the 1930s. They were used for bull-baiting and to chase wild game. This history means they are excellent runners and playful jumpers. The Boxer is used today by the police and military. Interestingly, in 2005, a Boxer’s DNA was used to sequence the canine genome.\r\n\r\nThe Boxer dog breed is deep-chested and is usually well-muscled under its smooth coat. They are considered a medium-sized dog breed—weighing in around 65-80 pounds with an average height of 21-23 inches.",
                            Name = "Boxer",
                            PictureName = "Boxer.jpg"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 3,
                            CategoryId = 1,
                            Description = "The English Cocker Spaniel is often described as “merry” because of his charming and happy personality. The dogs are popular across the world because of their hunting abilities and will work tirelessly to retrieve game birds. Their eager-to-please nature in the field is carried into the home as well, making them wonderful companions.",
                            Name = "English Cocker Spaniel",
                            PictureName = "English Cocker Spaniel.jpg"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 2,
                            CategoryId = 1,
                            Description = "First known as the Ainu, this dog breed was named after the people it lived with and later the area of Japan it was believed to have originated in. The Hokkaido is known as a great hunter as well as loveable and loyal pet.",
                            Name = "Hokkaido",
                            PictureName = "Hokkaido.jpg"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 4,
                            CategoryId = 1,
                            Description = "The Pug is an ancient dog breed that originated in China around 2,000 years ago. The Pug became a favorite of royals around the world, and today they are a very popular dog breed. They are easily identifiable due to their flat, wrinkly face, curly tail, and snorty, loud breathing.\r\n\r\nA Pug is typically 10 to 13 inches tall and weighs 14 to 18 pounds. They have short coats that are typically fawn (tan) or black.",
                            Name = "Pug",
                            PictureName = "Pug.jpg"
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 1,
                            CategoryId = 2,
                            Description = "In the initial years of breeding, the Balinese had heavier bones and apple shaped heads, more akin to the former standard Siamese. They also had much longer coats than the Balinese breed today, with full ruffs and britches. Over the years, Balinese breeders have improved the physical form of the breed by outcrossing it with the parent breed, the Siamese, and the features of the Balinese have become leaner and longer, just as the modern Siamese has. The breed standard for the Balinese is identical to the standard for the Siamese in most respects, including overall body type and color, with the obvious differences being in overall coat length, and in the full plume tail. The coat is single coated, with only minimal shedding. In fact, the Balinese is noted for its lack of shedding amongst long coated cats.",
                            Name = "Balinese",
                            PictureName = "Balinese.jpg"
                        },
                        new
                        {
                            AnimalId = 7,
                            Age = 3,
                            CategoryId = 2,
                            Description = "The Russian Blue is a robust breed, with firm muscles and an overall dose of good looks. It is physically in the same class as the Korat and Oriental Shorthair -- long, slender, elegant. It is of a medium size, and muscular, but compared to a swimmer in the compactness of its musculature. When it is in full motion and stretched out, one can see that it has a long, graceful neck, but the neck is hidden by thick fur and high set shoulder blades when the cat is sitting, making it look as though it has a short, thick neck.",
                            Name = "Russian Blue",
                            PictureName = "Russian Blue.jpg"
                        },
                        new
                        {
                            AnimalId = 8,
                            Age = 4,
                            CategoryId = 2,
                            Description = "The Siamese cat breed has strikingly large ears and attractive baby blue eyes. Their sleek, slim figure is accentuated by their short, fine coat with long tapering lines. The coat comes in four traditional colors: seal, chocolate, blue, and lilac point -- a pale body color with relatively darker extremities; i.e., the face, ears, feet and tail.",
                            Name = "Siamese Cat",
                            PictureName = "Siamese Cat.jpg"
                        },
                        new
                        {
                            AnimalId = 9,
                            Age = 1,
                            CategoryId = 2,
                            Description = "The Bengal cat is a long, muscular, medium- to  large-sized  cat, with a broad head and muzzle, high cheekbones, and pronounced whisker pads. The eyes are round and wide, with dark markings around the eyes (mascara) and the ears small and rounded at the tips. The grace of a jungle cat is held as one of the positive characteristics, along with the ability to move quietly and with stealth. The back legs are slightly longer than the front legs, making the hind end a bit higher than the shoulders, and emphasizing the Bengal's wild-cat appearance. The Bengal's muscular, athletic build is one of its most defining features; it is never delicate.",
                            Name = "Bengal House Cat",
                            PictureName = "Bengal House Cat.jpg"
                        },
                        new
                        {
                            AnimalId = 10,
                            Age = 2,
                            CategoryId = 2,
                            Description = "Colorpoint Shorthairs are the first-cousins of the Siamese, and are distinguished by their 16 different \"point\" colors beyond the four Siamese colors. Seldom quiet, they love entertaining and being entertained.",
                            Name = "Colorpoint Shorthair",
                            PictureName = "Colorpoint Shorthair.jpg"
                        },
                        new
                        {
                            AnimalId = 11,
                            Age = 1,
                            CategoryId = 3,
                            Description = "Betta fish are native to Asia, where they live in the shallow water of marshes, ponds, or slow-moving streams. Male bettas are devoted fathers who build bubble nests for their young with their mouths and fiercely protect their babies from predators. Just like us, betta fish are diurnal. That means they’re active during the day and sleep at night, requiring darkness to get a good night’s rest.",
                            Name = "Siamese fighting fish",
                            PictureName = "Siamese fighting fish.jpg"
                        },
                        new
                        {
                            AnimalId = 12,
                            Age = 2,
                            CategoryId = 3,
                            Description = "Goldfish have two sets of paired fins and three sets of single fins. They don’t have barbels, sensory organs some fish have that act like taste buds. Nor do they have scales on their heads. They also don’t have teeth and instead crush their food in their throats.\r\n\r\nThe fish are known for having large eyes and great senses of smell and hearing. Their ability to hear comes from small bones near their skull that link their swim bladder and their inner ear.",
                            Name = "Goldfish",
                            PictureName = "Goldfish.jpg"
                        },
                        new
                        {
                            AnimalId = 13,
                            Age = 1,
                            CategoryId = 3,
                            Description = "The Achilles Tang, also known as the Red-tailed Surgeon, or Achilles Surgeonfish, is very dark brown to purple. It has bright highlights of white and orange around the dorsal, caudal, and anal fins. A white marking is also present on the gill covers and a striking orange teardrop is found near the caudal fin. The juveniles of this species have an orange marking by the tail in the shape of a streak instead of being teardrop in shape.\r\nA 180 gallon aquarium or larger is necessary to provide plenty of swimming room,and these fishes require strong water flow as they are normally found in surge zones. It is aggressive towards other Tangs and Surgeonfish, but peaceful with other fish.",
                            Name = "Achilles Tang",
                            PictureName = "Achilles Tang.jpg"
                        },
                        new
                        {
                            AnimalId = 14,
                            Age = 2,
                            CategoryId = 3,
                            Description = "The red wagtail platy is a pleasant and peaceful freshwater fish that's both hardy and active. It's also small, pretty, and a great fish for hobbyists of any level; in fact, it's one of the most popular in the fishkeeping industry. You can find platies in several different colors which make for an eye-catching tank. The platy has two goals in life: eating and breeding. They will circle the tank eating anything, including algae, and their breeding can't be stopped. Like guppies, platies are livebearing fish.",
                            Name = "Red Platy",
                            PictureName = "Red Platy.jpg"
                        },
                        new
                        {
                            AnimalId = 15,
                            Age = 1,
                            CategoryId = 3,
                            Description = "The glowlight tetra is absolutely gorgeous and surprisingly easy to care for. Originating in the rivers of Guyana, it is easygoing and peaceful and can survive in a fairly wide range of aquarium environments. Because they are schooling fish, you'll want to keep at least six glowlight tetras.",
                            Name = "Glowlight Tetra Fish",
                            PictureName = "Glowlight Tetra Fish.jpg"
                        });
                });

            modelBuilder.Entity("Pet_Shop.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Dogs"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Cats"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Fishes"
                        });
                });

            modelBuilder.Entity("Pet_Shop.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CommentId");

                    b.HasIndex("AnimalId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentId = 1,
                            AnimalId = 1,
                            Text = "Pitbulls are Awesome!"
                        },
                        new
                        {
                            CommentId = 2,
                            AnimalId = 1,
                            Text = "Pitbulls are relaible."
                        },
                        new
                        {
                            CommentId = 3,
                            AnimalId = 2,
                            Text = "I love boxers!"
                        },
                        new
                        {
                            CommentId = 4,
                            AnimalId = 2,
                            Text = "Amazing dog."
                        },
                        new
                        {
                            CommentId = 5,
                            AnimalId = 2,
                            Text = "Good with childrens."
                        },
                        new
                        {
                            CommentId = 6,
                            AnimalId = 3,
                            Text = "Easy to train."
                        },
                        new
                        {
                            CommentId = 7,
                            AnimalId = 4,
                            Text = "Very smart dog."
                        },
                        new
                        {
                            CommentId = 8,
                            AnimalId = 4,
                            Text = "Like to be active."
                        },
                        new
                        {
                            CommentId = 9,
                            AnimalId = 5,
                            Text = "Beatiful dog."
                        },
                        new
                        {
                            CommentId = 10,
                            AnimalId = 6,
                            Text = "Quiet and playful cat."
                        },
                        new
                        {
                            CommentId = 11,
                            AnimalId = 6,
                            Text = "They Are Extremely Smart Cats."
                        },
                        new
                        {
                            CommentId = 12,
                            AnimalId = 7,
                            Text = "The Russian Blue are lovely cats"
                        },
                        new
                        {
                            CommentId = 13,
                            AnimalId = 8,
                            Text = "They’re one of the oldest cat breeds"
                        },
                        new
                        {
                            CommentId = 14,
                            AnimalId = 8,
                            Text = "Their coloring comes from albinism"
                        },
                        new
                        {
                            CommentId = 15,
                            AnimalId = 8,
                            Text = "A Siamese cat lived in the White House"
                        },
                        new
                        {
                            CommentId = 16,
                            AnimalId = 8,
                            Text = "Siamese kittens are born all white"
                        },
                        new
                        {
                            CommentId = 17,
                            AnimalId = 9,
                            Text = "Bengal cats tend to be medium to large in size."
                        },
                        new
                        {
                            CommentId = 18,
                            AnimalId = 9,
                            Text = "They might weigh between 8-15 pounds or more and range in height anywhere from about 13-16 inches tall."
                        },
                        new
                        {
                            CommentId = 19,
                            AnimalId = 10,
                            Text = "They have amazing eyes!"
                        },
                        new
                        {
                            CommentId = 20,
                            AnimalId = 11,
                            Text = "Siamese fighting fish can live in tiny tanks, because they live in little creeks in the wild"
                        },
                        new
                        {
                            CommentId = 21,
                            AnimalId = 11,
                            Text = "Betta fish don't need a filter because in the wild they live in muddy water"
                        },
                        new
                        {
                            CommentId = 22,
                            AnimalId = 11,
                            Text = "Bettas can breathe air, unlike other fish"
                        },
                        new
                        {
                            CommentId = 23,
                            AnimalId = 12,
                            Text = "Goldfish have been known to live for over 40 years"
                        },
                        new
                        {
                            CommentId = 24,
                            AnimalId = 12,
                            Text = "Goldfish can recognize peoples faces"
                        },
                        new
                        {
                            CommentId = 25,
                            AnimalId = 12,
                            Text = "Goldfish have a memory-span of at least three months"
                        },
                        new
                        {
                            CommentId = 26,
                            AnimalId = 12,
                            Text = "Goldfish can grow to over a foot long"
                        },
                        new
                        {
                            CommentId = 27,
                            AnimalId = 13,
                            Text = "Very expensive fish but beautiful"
                        },
                        new
                        {
                            CommentId = 28,
                            AnimalId = 14,
                            Text = "Red platy live for 3-4 years"
                        },
                        new
                        {
                            CommentId = 29,
                            AnimalId = 15,
                            Text = "Glowlight tetras are very peaceful and easy-going."
                        },
                        new
                        {
                            CommentId = 30,
                            AnimalId = 15,
                            Text = "A single female can produce 50 or more eggs in one spawn. "
                        });
                });

            modelBuilder.Entity("Pet_Shop.Models.Animal", b =>
                {
                    b.HasOne("Pet_Shop.Models.Category", "Category")
                        .WithMany("Animals")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Pet_Shop.Models.Comment", b =>
                {
                    b.HasOne("Pet_Shop.Models.Animal", "Animal")
                        .WithMany("Comments")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("Pet_Shop.Models.Animal", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Pet_Shop.Models.Category", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
